### ISSUE TITLE
요도 삽입 후 요도삽입 버튼 사라짐

### ISSUE THREAD

**Issue by qkskskclq7** [Riey/eraTHYMKR#104]
## 예상한 동작
요도 삽입 후 다시 요도삽입 버튼이 나올줄 알았음

## 실제 동작
요도삽입 후에 요도삽입 버튼이 사라짐

## 문제 재현 방법
1. 릴리 B(블랙) (다른캐릭터는 실험 안해봄) 조교로 요도삽입
1.
1.

## 동작환경
* 버전:  (190216)
* OS: 안드로이드
* 런쳐: uEmuera

**Comment by Riey** [comment]
저는 재현이 되지 않았습니다 릴리B는 요정이라 기력이 낮은데 조건중에 기력 500이상이 있으니 확인해 보세요

**Comment by Riey** [comment]
기력조건 확인해보시고 다른 문제있으면 다시 열어주세요
