### ISSUE TITLE
'괴뢰' 및 '괴조인격'의 스케줄에 따른 스트레스 에러

### ISSUE THREAD

**Issue by bjkim9805** [Riey/eraTHYMKR#109]
## 예상한 동작
아무리 체력을 단련시키든 모유를 뽑아내든 스트레스가 쌓이지 않음

## 실제 동작
니토리의 스트레스 +24

## 문제 재현 방법
1. 누군가 한명정도 괴뢰 또는 괴조인격으로 만든다.
2. 스트레스가 이론상 절대 쌓이지 않을 만한 캐릭터에게 스트레스가 쌓이는 스케줄을 부여한다.
3. 스트레스 +

## 동작환경
* 버전: 20190608
* OS: 관계없음
* 런쳐: 기본

**Comment by Riey** [comment]
#111 에서 수정됐습니다 master에 올라오면 닫겠습니다
