### ISSUE TITLE
era 관련 커뮤니티 사용자들이 업로드하는 구상을 도입할 계획이 있어 문의합니다.

### ISSUE THREAD

**Issue by 63cr** [Riey/eraTHYMKR#110]
현재 era 관련 커뮤니티에서는 사용자들이 활발하게 게임에 관련된 구상 형식 연재물이 연재하고 있습니다.
이 중 오줌싸개버릇 취득 구상 연재물과 주인 임신 구상 연재물은 조건과 내용이 구체적이라 즉시 도입해도 될 정도로 보고 있어서 eraTHYMKR에 도입을 추진하려고 합니다.
연재자 분들에게 허가는 맡았으며 추가적으로 기여자 및 출처 공개 등에 대해서도 문의할 계획입니다.
이러한 창작물들을 정식적으로 eraTHYMKR에 추가해도 되는지 여쭙고 싶습니다.

**Comment by Riey** [comment]
쓴 사람한테 허락 맡으셨으면 넣으셔도 됩니다

**Comment by 63cr** [comment]
감사합니다. 며칠 안으로 연재자 분들과 추가적인 사항을 협의한 뒤 commit을 올리겠습니다.
