### ISSUE TITLE
[RFC]  사쿠야 엔딩 수정

### ISSUE THREAD

**Issue by marints** [Riey/eraTHYMKR#112]

**Comment by Riey** [comment]
이건 Pull Request로 올리시는게 좋아보입니다

제가 직접 패치해드릴순 있는데 피드백 받기가 힘들어서 임의로 여기저기 칼질당할수도 있어요

**Comment by marints** [comment]
> ## 요약
> 사쿠야의 엔딩이 급전개가 되는걸 수정했음.
> 
> ## 상세
> 사쿠야 엔딩은 크게 노예엔딩과 순애엔딩이 있음.
> 
> 그런데 사쿠야 순애엔딩은 조건도 이상하리만큼 복잡하고, 스토리 내용도 사쿠야한테 되려 뒤를잡혀서 사쿠야한테 부려먹히고
> 
> 착정섹스당하는 펨돔물 스토리인데, 결말부만 보면 갑자기 순애물이 됨.
> 
> 대체 씨발 왜 이런거지 씨발?? 하고 찾아봤더니, 2012년 쯔음 사쿠야 루트 진엔딩, 그러니까 비 노예화 엔딩은 지금처럼 달달한 그것이 아니었음.
> 
> 2012년 기준 사쿠야 엔딩자료를 찾아보니 비교적 정상적인? 기존의 진엔딩 루트와 어울리는 엔딩이 있었고, 이게 마음에 안들었던 모 인물이 수정해서 앞에는 펨돔찍다가 엔딩에서 순애 급회전하는 이상한 엔딩이 나왔던걸로 판단했음.
> 
> 그래서 구 엔딩을 적당히 수정해서 적당히 맞게 고치고, 진엔딩을 인게이지링 엔딩으로, 인게이지링 엔딩(노예엔딩) 을 노예화 엔딩으로 옮겨놨음.
> 
> ## 해결되지 않은 질문
> 솔직히말해서, 펨돔루트가 있으면 노예화 루트도 따로 있으면 좋겠다고 생각하지만, 에라 언어를 그렇게 잘아는게 아니라서, 필력이 좋지 못해서 제대로 할 수 있을지 모르겠음.
> 
> 메가 링크
> 
> https://mega.nz/#!MmJDFCiY!h3XC_u_KynSezvuKYXWcYB2XCt9FGuH16W9BgErdVO0
