### ISSUE TITLE
실적 달성 시 공략한 캐릭터와 다른 캐릭터로 클리어된 것으로 처리되는 문제.

### ISSUE THREAD

**Issue by 63cr** [Riey/eraTHYMKR#29]
## 관련파일
https://github.com/Riey/eraTHYMKR/blob/master/ERB/SYS/SHOP_CHARABUY.ERB

## 원인
어떤 캐릭터를 처음 골랐는지 저장하는 FLAG:250이 결정되는 순간이 구입 시가 아닌 구입 전 캐릭터 정보 열람 시이기 때문입니다.

## 해결 방법 제안
137번째 줄에 있는 다음 코드를
```
137 ;最初に購入したかどうか, してなければ選んだ番号を入れる
138 SIF FLAG:250 == 0
139     FLAG:250 = LOCAL:2
```
현 버전 기준 163번째 줄로 이동하면 됩니다.

```
159 ELSE
160     LOCALS = ＜%조사처리(CSVNAME(LOCAL:2,0),"를")% 구입했다.＞
161     MONEY -= ITEMSALES:(LOCAL:1)
162 ENDIF
163 
164 ;購入した奴隷を表記
165 SIF TFLAG:209 == 1
```

**Comment by Riey** [comment]
## 일정

- [ ] 파일수정
- [ ] 수정된 파일 커밋
- [ ] 커밋으로 pull request 생성
- [ ] master에 merge

**Comment by Riey** [comment]
커밋완료 https://github.com/Riey/eraTHYMKR/commit/a6de572abe1bf00ac50b623e204afa3e3a0a8308

**Comment by Riey** [comment]
pull request생성 및 merge완료 #30

**Comment by Riey** [comment]
파일경로를 커밋기준으로 변경했습니다
