### ISSUE TITLE
조교계 모든 실적 달성을 충족할 수 없는 문제.

### ISSUE THREAD

**Issue by 63cr** [Riey/eraTHYMKR#34]
## 관련파일
https://github.com/Riey/eraTHYMKR/blob/master/ERB/SYS/TROPHY.ERB

## 원인
조교계 실적 처리는 GLOBAL:201에서 각 비트 자릿수마다 배정돼 있습니다. GLOBAL:201의 2^0 부분은 모든 조교계 실적 달성을 의미하며 나머지 2^1부터 2^14까지는 그 외 조교계 실적 처리를 담당합니다. 이에 따르면 모든 조교계 실적 달성을 의미하는 값은 2^15 - 2가 되는데 조건문에는 계산 착오로 2^16 - 2를 넣었습니다.

## 해결 방법 제안
```
189 SIF GLOBAL:201 == 65534
190     GLOBAL:201 |= 1p0
191 
192 SIF GLOBAL:200 == 1048574 && GLOBAL:201 == 65535 && GLOBAL:202 == 144115188075855871
193     GLOBAL:200 |= 1p0
```
위 코드를 다음과 같이 변경하면 됩니다.
```
189 SIF GLOBAL:201 == 32766
190     GLOBAL:201 |= 1p0
191 
192 SIF GLOBAL:200 == 1048574 && GLOBAL:201 == 32767 && GLOBAL:202 == 144115188075855871
193     GLOBAL:200 |= 1p0
```

**Comment by Riey** [comment]
## 수정커밋
https://github.com/Riey/eraTHYMKR/commit/e1019cba39e164f319a99055ebfe27f85a8f959e
