### ISSUE TITLE
이번에 추가한 IS_COM_INSERT 코드와 이 코드를 같은 위치에 둬야할 것 같습니다

### ISSUE THREAD

**Issue by Rufel** [Riey/eraTHYMKR#54]
https://github.com/Riey/eraTHYMKR/blob/c151e6c8588d28b28e9fc355e66ca21710ecc0cd/ERB/COM/COM_FUNCTION.ERB#L590
이건 자위 판정 코드네요.

**Comment by Riey** [comment]
그렇네요 좀 있다가 정리하겠습니다

**Comment by Riey** [comment]
정리했습니다

https://github.com/Riey/eraTHYMKR/commit/0ba4faf8eed752d50e3884c10a314c3d5bd394c6

**Comment by Rufel** [comment]
감사합니다
