### ISSUE TITLE
Event_shoot을 옮겨야할 것 같습니다.

### ISSUE THREAD

**Issue by Rufel** [Riey/eraTHYMKR#57]
Event_shoot이랑 System_shoot이랑 관련도 크고 Event도 아닌 것 같습니다.
파일명을 마음대로 바꿀 수 있다면 System_shoot2가 나을 것 같아요.

**Comment by Rufel** [comment]
그렇군요 감사합니다

**Comment by Riey** [comment]
단순히 취소하는건 reset으로 가능하고
복잡한 작업은 rebase로 가능합니다

**Comment by Rufel** [comment]
감사합니다
