### ISSUE TITLE
"조교 메뉴 등록" 탭에서의 비정상 커멘드

### ISSUE THREAD

**Issue by SubroutineUser** [Riey/eraTHYMKR#58]
<h1>[691] 식사</h1>

- 조교 메뉴 등록 과정에서는 에러가 발생하지 않지만, 실행 시 에러가 발생함.
- Train.CSV 파일에서는 토리코 모드 전용이라고 나와있지만, 토리코 모드가 아닐 때에도 표기됩니다.

프레임워크 구조를 제대로 알지를 못해서 디버깅 및 수정 작업을 제가 직접 하기에는 꽤 어려울거 같아서 일단 이슈로 올려둡니다.

<h1>Log</h1>
COM\COM_REGISTER.ERBの182行目でエラーが発生しました:Emuera1818_kr3
    CALLFORM COM_ABLE{FLAG:(551 + COUNT)}
エラー内容：関数"@COM_ABLE691"が見つかりません
現在の関数：@COMSEQ_TRAIN（COM\COM_REGISTER.ERBの172行目）
関数呼び出しスタック：
↑SYS\TRAIN_USERCOM.ERBの226行目（関数@USERCOM内）

**Comment by Riey** [comment]
https://github.com/Riey/eraTHYMKR/commit/d653cf1375e4a31e79dd0c9802b42de884e99046

691번 커맨드는 함수도없고 쓰지도 않는 껍데기라 삭제했습니다

이제 버그는 안날것같네요
