### ISSUE TITLE
식사 모드

### ISSUE THREAD

**Issue by Rufel** [Riey/eraTHYMKR#60]
날짜가 바뀌어서, 캐릭터가 20명이 넘어서 밥을 먹으면 페이지를 넘길때마다 돈이 나갑니다.  돈이 무한정나가고 먹었는지 안먹었는지도 계속 바뀌네요.

어떻게 고쳐야할지 몰라서 올립니다.

**Comment by Riey** [comment]
세이브 파일 올려주실래요?

**Comment by Rufel** [comment]
[era sav.zip](https://github.com/Riey/eraTHYMKR/files/1966117/era.sav.zip)

일상생활휴식 몇번 누르시면 식사시간 보이실 거에요.
1009 1001 누를 때마다 돈이 나가요. 결과값도 계속 바뀌고요.

**Comment by Riey** [comment]
https://github.com/Riey/eraTHYMKR/commit/78bda00d63fd3b08965e2729874d6719a3e30b5a

일단 간단하게 수정해봤는데 시험해보세요

**Comment by Rufel** [comment]
잘 되는 것 같네요. 감사합니다.
