### ISSUE TITLE
아침 이벤트 대사 중복 출력

### ISSUE THREAD

**Issue by keffred** [Riey/eraTHYMKR#64]

**Comment by Riey** [comment]
어떤 상황에서 일어난거죠?

**Comment by keffred** [comment]
이전 릴리즈에서 현 릴리즈로 업그레이드시 세이브 파일 이상인지 몰라도 첫 아침 이벤트 대사가 중복으로 일어나네요.

두번째 아침 이벤트 부터는 정상적으로 작동합니다.

**Comment by Riey** [comment]
세이브 파일을 업로드해주실수 있으신가요? 저는 재현이 안되네요

**Comment by keffred** [comment]
세이브 새로하니 더이상 재현이 안되긴 한데;;
일단 드리겠습니다. 

https://goo.gl/C8UnHD

**Comment by keffred** [comment]
이전 릴리즈에서 현 릴리즈로 업그레이드시 세이브 파일 이상으로 초기 한번만 간헐적으로 일어나는것으로 보입니다만...

**Comment by Riey** [comment]
받은 세이브로도 못보겠네요

97번 98번 세이브를 로드해봤지만 한번만 나옵니다

**Comment by Riey** [comment]
일시적인 문제같은데 일단 종결처리 해도 되겠습니까?

**Comment by keffred** [comment]
아무래도 일시적인 문제 같습니다. 종결 부탁드립니다.
