### ISSUE TITLE
캐릭터 정렬 커멘드

### ISSUE THREAD

**Issue by SubroutineUser** [Riey/eraTHYMKR#71]
캐릭터 정렬 커맨드에서 페이지 이동이 되지 않습니다.

다음 페이지를 클릭해도 같은 캐릭터들만 나오네요.

표시 페이지 값은 올라갑니다만, 표시는 1페이지의 캐릭터만 보이네요.

**Comment by Riey** [comment]
수정해봤습니다

https://github.com/Riey/eraTHYMKR/commit/cfd51b89bbe70db09f512fc2c806fa1dd1406840

**Comment by Riey** [comment]
답변이 없어서 된걸로 알고 닫습니다
