### ISSUE TITLE
삭제한 txt파일에 관해서....

### ISSUE THREAD

**Issue by Rufel** [Riey/eraTHYMKR#81]
K10, 레밀리아 cflag.txt는 복원해야 합니다.
K227, 플래그자료도 복원해야 합니다.

애매한 것 :
K72 코가사 플래그자료, 그런데 인코딩이 박살나 있어서 숫자만 읽을 수 있음.
K82, K81 , txt만 한글이고 erb는 일본어임. 그러나 번역판은 아님.
K100 미마 수정전 erb파일 인코딩이 깨져있음.
Etc의 2014갱신로그.txt 이벤트조건(내용누설주의).txt도 인코딩이 깨진 것 같습니다. 그런데 웹에서는 제대로 읽힙니다

**Comment by Riey** [comment]
초기버전에서 땡겨와보겠습니다

**Comment by Riey** [comment]
https://github.com/Riey/eraTHYMKR/commit/6f4b9982186e8e7b97bd9b7b9ec20aa88e32b334
https://github.com/Riey/eraTHYMKR/commit/58fceb569ab7e28ab97b5b1d6c2ccfa53a6679a6

레밀이랑 라이코 코가사만 복원해봤습니다 갱신로그는 UTF-8달려서 멀쩡한거같은데요

**Comment by Rufel** [comment]
https://github.com/Riey/eraTHYMKR/blob/0d64c81c2af2c06d4adde31e4dcc1e1429e36063/etc/%EA%B0%9C%EB%B0%9C%20%EC%9E%90%EB%A3%8C/%EC%9D%B4%EB%B2%A4%ED%8A%B8%EC%A1%B0%EA%B1%B4(%EB%82%B4%EC%9A%A9%EB%88%84%EC%84%A4%EC%A3%BC%EC%9D%98!).txt#L1

**Comment by Rufel** [comment]
https://github.com/Riey/eraTHYMKR/blob/0d64c81c2af2c06d4adde31e4dcc1e1429e36063/etc/%EA%B0%9C%EB%B0%9C%20%EC%9E%90%EB%A3%8C/2014%EC%8B%A0%ED%86%B5%ED%95%A9%ED%8C%90%20%EA%B0%B1%EC%8B%A0%EB%A1%9C%EA%B7%B8.txt#L247

**Comment by Rufel** [comment]
https://github.com/Riey/eraTHYMKR/tree/53ac1868bc1ea9ea6365e7a0e3d373e85c342940/etc/%EA%B0%9C%EB%B0%9C%20%EC%9E%90%EB%A3%8C
여기에선 멀쩡하네요.

**Comment by Riey** [comment]
제보해주신거 참고해서 수정해봤니다

https://github.com/Riey/eraTHYMKR/commit/90ed235c66a7e87e710919b4d9bb84238bffb0ec

**Comment by Rufel** [comment]
Binary file not shown이라고 뜨는데...
원래 이런건가요?
VIEW누르면 글자는 안 깨지네요.

**Comment by Riey** [comment]
예전 깨진파일의 인코딩을 인식못해서 바이너리 뜨는것같습니다 지금은 고쳐져서 텍스트로 인식되고요

**Comment by Riey** [comment]
더 추가할거 있나요? 지금까지 레밀리아 라이코 코가사랑 개발자료 2개 복구했습니다

**Comment by Rufel** [comment]
과거 갱신 이력이 남겨둬야 하는 건지 몰라서 그러는데, 레밀리아, 리리카 갱신이력도 존재해요. 근데 너무 오래되서 복구할 필요는 없어보이고요.
미마.erb 깨진 건 왜 남겨두신건가요?

**Comment by Riey** [comment]
갱신이력은 필요없는거같고 미마는 빼먹었네요

**Comment by Rufel** [comment]
네. 감사합니다.
