### ISSUE TITLE
여쭤보고 싶은 것이 있습니다.

### ISSUE THREAD

**Issue by WorldBear** [Riey/eraTHYMKR#89]
## 질문
 1. 탈자궁과 유사한 '탈장 (Prolapse)' 관련 커맨드를 구상중입니다. 소질로 '탈장' 항목을 넣어야 하고, '탈장유도제' 아이템과 '탈장유도약' 체질변화약, 그리고 조교 커맨드에 '탈장주사', '탈장', '탈장오나홀'을 넣고 싶습니다. 구현하려면 어느어느 파일들을 건드려야 할까요?
 2. 위 질문과 일부 겹치는 부분이 있습니다만, 파생 커맨드는 어떻게 만들 수 있을까요? '애널삽입자궁자극', '애널삽입S자결장자극' 등의 커맨드를 추가하고 싶습니다.

**Comment by Riey** [comment]
1.

커맨드는 train.csv에서 추가하시고 구현을 ERB/COM에 넣으시면 됩니다

소질은 talent.csv

아이템은 item.csv에 넣으시면 0~99번까지는 일반 상점에 자동으로 표시되고

체질변화쪽은 ERB/SYS/SHOP/SHOP_DRUGSTORE.ERB 여기 약방에 직접 넣으셔야겠네요

----

2.

파생 커맨드는 위에 말씀드린거처럼 추가 해놓고

우선 이렇게 COM_ABLE을 끕니다(이러면 커맨드가 직접 표시/선택 되지 않습니다)
https://github.com/Riey/eraTHYMKR/blob/eff552b06f97f7452d4f6ce742ea8ffd085d6e63/ERB/COM/COMF6's/COMF616.ERB#L7-L9

그리고 이렇게 파생커맨드를 만들 커맨드 본체에 분기를 추가해서 들어가시면 됩니다

https://github.com/Riey/eraTHYMKR/blob/eff552b06f97f7452d4f6ce742ea8ffd085d6e63/ERB/COM/COMF0's/COMF003.ERB#L23-L30
